version: '3.8'

services:
  app: 
    build: .
    command: yarn run dev
    ports:
     - '3000:3000'
    volumes:
      - .:/usr/app
  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017      