version: '3.8'

services:
  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
  # app:
  #   build: .
  #   command: npm run dev
  #   ports:
  #    - '3000:3000'
  #   volumes:
  #     - .:/usr/app